name: Deploy Terraform Infrastructure

on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/entra/**'
      - '.github/workflows/deploy-terraform.yml'

jobs:
  terraform:
    uses: spectrum048k/github-templates/.github/workflows/terraform-ci.yml@main
    with:
      working-directory: infrastructure/entra
      checkov-path: infrastructure/entra
    secrets:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}